// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-contacts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-contacts.ts
var list_contacts_default = defineTool({
  name: "list_contacts",
  title: "Listar mensagens de contato",
  description: "Lista as mensagens recebidas pelo formul\xE1rio de contato do site (requer conta de administrador).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Quantidade m\xE1xima de mensagens."),
    search: z.string().trim().min(1).optional().describe("Filtro por nome ou e-mail.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contacts").select("id,name,email,phone,service,message,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-portfolio-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_portfolio_projects_default = defineTool2({
  name: "list_portfolio_projects",
  title: "Listar projetos do portf\xF3lio",
  description: "Lista os projetos do portf\xF3lio do site, opcionalmente filtrados por categoria.",
  inputSchema: {
    category: z2.string().trim().min(1).optional().describe("Slug da categoria (ex.: criativos)."),
    limit: z2.number().int().min(1).max(100).default(50).describe("Quantidade m\xE1xima de projetos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("portfolio_projects").select("id,title,category,category_label,description,price,image_url,sort_order,updated_at").order("sort_order", { ascending: true }).limit(limit ?? 50);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-portfolio-project.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_portfolio_project_default = defineTool3({
  name: "create_portfolio_project",
  title: "Criar projeto no portf\xF3lio",
  description: "Cria um novo projeto no portf\xF3lio do site (requer conta de administrador). A imagem deve ser uma URL p\xFAblica.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("T\xEDtulo do projeto."),
    category: z3.string().trim().min(1).describe("Slug da categoria (ex.: criativos)."),
    category_label: z3.string().trim().min(1).describe("Nome exibido da categoria."),
    image_url: z3.string().url().describe("URL p\xFAblica da imagem de capa."),
    description: z3.string().trim().min(1).optional().describe("Descri\xE7\xE3o do projeto."),
    price: z3.string().trim().min(1).optional().describe("Pre\xE7o exibido (texto livre)."),
    sort_order: z3.number().int().min(0).optional().describe("Ordem de exibi\xE7\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolio_projects").insert({
      title: input.title,
      category: input.category,
      category_label: input.category_label,
      image_url: input.image_url,
      description: input.description ?? null,
      price: input.price ?? null,
      ...input.sort_order === void 0 ? {} : { sort_order: input.sort_order }
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/update-portfolio-project.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var update_portfolio_project_default = defineTool4({
  name: "update_portfolio_project",
  title: "Atualizar projeto do portf\xF3lio",
  description: "Atualiza campos de um projeto existente do portf\xF3lio, como t\xEDtulo, pre\xE7o, descri\xE7\xE3o ou imagem (requer conta de administrador).",
  inputSchema: {
    id: z4.string().uuid().describe("ID do projeto a atualizar."),
    title: z4.string().trim().min(1).optional(),
    category: z4.string().trim().min(1).optional(),
    category_label: z4.string().trim().min(1).optional(),
    image_url: z4.string().url().optional(),
    description: z4.string().trim().optional(),
    price: z4.string().trim().optional(),
    sort_order: z4.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const patch = Object.fromEntries(
      Object.entries(fields).filter(([, value]) => value !== void 0)
    );
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "Nenhum campo para atualizar." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolio_projects").update(patch).eq("id", id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Projeto n\xE3o encontrado ou sem permiss\xE3o." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cczzhkxomtwgovwdvstf";
var mcp_default = defineMcp({
  name: "agencia-kaeth",
  title: "Ag\xEAncia Kaeth",
  version: "0.1.0",
  instructions: "Ferramentas da Ag\xEAncia Kaeth. Use `list_contacts` para ler mensagens do formul\xE1rio de contato e `list_portfolio_projects`, `create_portfolio_project` e `update_portfolio_project` para gerenciar o portf\xF3lio do site. Todas as a\xE7\xF5es rodam como o usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_contacts_default,
    list_portfolio_projects_default,
    create_portfolio_project_default,
    update_portfolio_project_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
